#!/usr/bin/python3

import sys
import zlib
import json
import getopt
import datetime
from struct import unpack

FTEXT = 1
FHCRC = 2
FEXTRA = 4
FNAME = 8
FCOMMENT = 16

XFL_BEST_COMPRESSION = 2
XFL_FAST_COMPRESSION = 4

GZIP_MAGIC = (0x1f, 0x8b)
ENCODING = 'latin-1'

COMPRESSION_METHOD = {
    8: 'deflate'
}

OPERATING_SYSTEM = {
    0: 'FAT filesystem (MS-DOS, OS/2, NT/Win32)',
    1: 'Amiga',
    2: 'VMS (or OpenVMS)',
    3: 'Unix',
    4: 'VM/CMS',
    5: 'Atari TOS',
    6: 'HPFS filesystem (OS/2, NT)',
    7: 'Macintosh',
    8: 'Z-System',
    9: 'CP/M',
    10: 'TOPS-20',
    11: 'NTFS filesystem (NT)',
    12: 'QDOS',
    13: 'Acorn RISCOS',
    255: 'unknown',
}

def read_string(fp):
    res = b''
    while 1:
        c = fp.read(1)
        if not c:
            raise ValueError # ???
        if c == b'\0':
            break
        res += c
    return res

def decode_bytes(buf):
    return buf.decode(ENCODING, errors='latin-1')

def parse_ext(buf):
    res = []
    while buf:
        si1, si2, slen = unpack('<BBH', buf[:4])
        data = buf[4:4+xlen]
        res.append((si1, si2, slen, decode_bytes(data)))
        buf = buf[4+slen:]
    return res

def read_member(fp, include_data=False):
    buf = fp.read(10)
    if not buf:
        return None # EOF

    m = dict(zip(
        ('id1', 'id2', 'cm', 'flg', 'mtime', 'xfl', 'os'),
        unpack('<BBBBIBB', buf)
    ))
    if (m['id1'], m['id2']) != GZIP_MAGIC:
        raise ValueError('garbage data found: %s' % buf)

    if m['flg'] & FEXTRA:
        m['xlen'] = unpack('<H', fp.read(2))[0]
        m['xdata'] = parse_ext(fp.read(m['xlen']))

    if m['flg'] & FNAME:
        m['name'] = decode_bytes(read_string(fp))

    if m['flg'] & FCOMMENT:
        m['comment'] = decode_bytes(read_string(fp))

    if m['flg'] & FHCRC:
        m['crc16'] = unpack('<H', fp.read(2))

    zobj = zlib.decompressobj(-zlib.MAX_WBITS)
    data = b''
    while 1:
        decoded = zobj.decompress(fp.read(4096))
        if include_data:
            data += decoded
        if zobj.unused_data:
            fp.seek(-len(zobj.unused_data), 1)
            break
    decoded = zobj.flush()
    if include_data:
        m['data'] = decode_bytes(data)

    m['crc32'], m['isize'] = unpack('<II', fp.read(8))
    return m

def humanize(m):
    if m['os'] in OPERATING_SYSTEM:
        m['os'] = OPERATING_SYSTEM[m['os']]
    if m['cm'] in COMPRESSION_METHOD:
        m['cm'] = COMPRESSION_METHOD[m['cm']]

    flg = []
    if m['flg'] & FTEXT:
        flg.append('FTEXT')
    if m['flg'] & FHCRC:
        flg.append('FHCRC')
    if m['flg'] & FEXTRA:
        flg.append('FEXTRA')
    if m['flg'] & FNAME:
        flg.append('FNAME')
    if m['flg'] & FCOMMENT:
        flg.append('FCOMMENT')

    m['flg'] = flg

    xfl = []
    if m['xfl'] & XFL_BEST_COMPRESSION:
        xfl.append('BEST_COMPRESSION')
    if m['xfl'] & XFL_FAST_COMPRESSION:
        xfl.append('FAST_COMPRESSION')

    m['xfl'] = xfl

    mtime = datetime.datetime.utcfromtimestamp(m['mtime'])
    m['mtime'] = '%s UTC' % mtime
    return m

def usage():
    print('Usage: gziptext [-h] [-v] FILE1 [FILE2...]', file=sys.stderr)

def main():
    opts, args = getopt.getopt(sys.argv[1:], 'hv')

    if not args:
        usage()
        return 1

    verbose = 0

    for k, v in opts:
        if k == '-h':
            usage()
            return 0
        elif k == '-v':
            verbose += 1

    for path in args:
        with open(path, 'rb') as fp:
            while 1:
                m = read_member(fp, include_data=verbose>1)
                if not m:
                    break
                if verbose > 0:
                    m = humanize(m)
                json.dump(m, sys.stdout, sort_keys=1)
                sys.stdout.write('\n')
    return 0

if __name__ == '__main__':
    sys.exit(main())
